[package]
name = "aicp-executor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aicp-adapter-api = { path = "../aicp-adapter-api" }
aicp-core = { path = "../aicp-core" }
aicp-plan = { path = "../aicp-plan" }
thiserror.workspace = true

[dev-dependencies]
uuid.workspace = true
aicp-adapter-mock = { path = "../aicp-adapter-mock" }
