[package]
name = "aicp-demo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aicp-adapter-adaptive-db = { path = "../aicp-adapter-adaptive-db" }
aicp-adapter-ace = { path = "../aicp-adapter-ace" }
aicp-adapter-api = { path = "../aicp-adapter-api" }
aicp-adapter-mock = { path = "../aicp-adapter-mock" }
aicp-assurance = { path = "../aicp-assurance" }
aicp-capability = { path = "../aicp-capability" }
aicp-core = { path = "../aicp-core" }
aicp-executor = { path = "../aicp-executor" }
aicp-intent = { path = "../aicp-intent" }
aicp-planner = { path = "../aicp-planner" }
anyhow.workspace = true
